export const ACTIONS = {};

export enum ACTIONS_TYPES {
  ADMIN_PAGE_IMPORTED_PAGE_SET_SELECTED_ITEM = 'ADMIN_PAGE/IMPORTED_PAGE/SET_SELECTED_ITEM',
  ADMIN_PAGE_IMPORTED_PAGE_SET_SELECTED_PAGE = 'ADMIN_PAGE/IMPORTED_PAGE/SET_SELECTED_PAGE',
  ADMIN_PAGE_OBJECT_PAGE_SET_SELECTED_ITEM = 'ADMIN_PAGE/OBJECT_PAGE/SET_SELECTED_ITEM',
  ADMIN_PAGE_OBJECT_PAGE_SET_SELECTED_PAGE = 'ADMIN_PAGE/OBJECT_PAGE/SET_SELECTED_PAGE',
}
